// Generated by https://quicktype.io
class Notarias {
  List<Notaria> items = new List();
  
  Notarias();

  Notarias.fromJsonList (List<dynamic> jsonList) {
    if(jsonList == null) return;
    for(var item in jsonList){
      final notaria = new Notaria.fromJsonMap(item);
      items.add(notaria);
    }
  }

}



class Notaria {
  String identificador;
  String nombre;
  String provincia;
  String canton;
  String direccion;
  String telefonos;
  String notario;
  String descripcion;
  String latitudMapa;
  String longitudMapa;
  String provinciaMapa;
  String email;
  String horario;
  String contentType;
  String foto;
  List<NotariosPasivo> notariosPasivos;

  Notaria({
    this.identificador,
    this.nombre,
    this.provincia,
    this.canton,
    this.direccion,
    this.telefonos,
    this.notario,
    this.descripcion,
    this.latitudMapa,
    this.longitudMapa,
    this.provinciaMapa,
    this.email,
    this.horario,
    this.contentType,
    this.foto,
    this.notariosPasivos,
  });

  Notaria.fromJsonMap(Map<String, dynamic> json) {
    identificador = json['identificador'];
    nombre = json['nombre'];
    provincia = json['provincia'];
    canton = json['canton'];
    direccion = json['direccion'];
    telefonos = json['telefonos'];
    notario = json['notario'];
    descripcion = json['descripcion'];
    latitudMapa = json['latitudMapa'];
    longitudMapa = json['longitudMapa'];
    provinciaMapa = json['provinciaMapa'];
    email = json['email'];
    horario = json['horario'];
    contentType = json['content_Type'];
    foto = json['foto'];
  }

}


class NotariosPasivo {
  String identificador;
  String nombre;
  String descripcion;
  dynamic contentType;
  dynamic foto;

  NotariosPasivo({
    this.identificador,
    this.nombre,
    this.descripcion,
    this.contentType,
    this.foto,
  });
}

